name: wheel

on: [push, workflow_dispatch]

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Reorganize repository
      run: |
        git config user.email ""
        git config user.name "dummy"
        git subtree add --prefix python/subprojects/minpack . HEAD
        git mv python/{mesonpep517,pyproject}.toml
        git commit -m "Python dist"
    - run: |
        pipx run build . --sdist
      working-directory: python
    - uses: echapmanFromBunnings/upload-artifact@3.0.0
      with:
        name: minpack-python-sdist
        path: python/dist/*.tar.gz
        retention-days: 5

  manylinux:
    needs:
      - sdist
    runs-on: ubuntu-latest
    container: condaforge/linux-anvil-cos7-x86_64
    strategy:
      fail-fast: false
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']

    defaults:
      run:
        shell: ${{ matrix.shell || 'bash -l {0}' }}

    steps:
    - name: Create environment
      run: >-
        mamba create -n wheel
        --yes
        c-compiler
        fortran-compiler
        python=${{ matrix.python }}
        auditwheel
        git
        python
        pip
        python-build
        pkgconfig
        patchelf
        cffi
        numpy
        meson
        unzip
        wheel
    - name: Download sdist
      uses: aochmann/actions-download-artifact@1.0.4
      with:
        name: minpack-python-sdist
    - name: Build wheel
      run: |
        conda activate wheel
        set -ex
        tar xvf minpack-*.tar.gz
        python -m build minpack-*/ --wheel
        auditwheel show minpack-*/dist/*.whl
        auditwheel repair -w minpack-*/dist minpack-*/dist/*.whl --plat ${{ env.plat }}
        rm minpack-*/dist/*-linux_x86_64.whl
      env:
        plat: manylinux${{ matrix.python == '3.6' && '2010' || '_2_12' }}_x86_64
    - uses: echapmanFromBunnings/upload-artifact@3.0.0
      with:
        name: minpack-python-${{ matrix.python }}
        path: minpack-*/dist/*.whl
        retention-days: 5
